<section class="content">
	<div class="box no-border" style="margin-bottom:10px">
<style>
.ttHead{ text-align:center; margin:0}
.ttCnt{ text-align:center; margin-top:10px; margin-bottom:0;}
.tINst{background-color: #eee;padding: 10px;margin: -5px 10px 20px 10px;font-weight: 600;letter-spacing: 0.5px;}
	</style>
		<div class="box-body row" >
			<div class="col-md-4">
				<h4 class="ttHead">Total Tickets</h4>
				<h2 class="ttCnt"><?php echo count($my_tickets_listing);?></h2>
			</div>
			<div class="col-md-4">
				<h4 class="ttHead">Open Tickets</h4>
				<h2 class="ttCnt"><?php echo $openTickets;?></h2>
			</div>
			<div class="col-md-4">
				<h4 class="ttHead">Closed Tickets</h4>
				<h2 class="ttCnt"><?php echo $closedTickets;?></h2> 
			</div>
		</div> 
	</div>
	 <div class="box no-border">
		<div class="box-body row" >
			<!-- <div class="row tINst">
				<div class="col-xs-2"> <span style="color: #008000;font-size:10px;"><i class="fa fa-circle"></i></span> &nbsp;Alert Level 1</div>
				<div class="col-xs-2"> <span style="color: #FFBF00;font-size:10px;"><i class="fa fa-circle"></i></span> &nbsp;Alert Level 2 </div> 
				<div class="col-xs-2"> <span style="color: #FF681F;font-size:10px;"><i class="fa fa-circle"></i></span> &nbsp;Alert Level 3 </div> 
				<div class="col-xs-2"> <span style="color: #FF0000;font-size:10px;"><i class="fa fa-circle"></i></span> &nbsp;Alert Level 4</div>
			</div> -->
			<div class="col-xs-12 table-responsive">
				 
				<table class="table table-striped" id="table_recordtbl">
					<thead>
						<tr>
							<th width="1%">#</th>
							<th>Ticket ID</th>
							<th>Date &amp; Time</th>
							<th>Type</th>
							<th>Generated By</th>
							<th>Conversation</th>
							<th>Last Update</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						<?php 
							$d2 = date('Y-m-d');
						if(count($my_tickets_listing)>0){ $i=1;foreach($my_tickets_listing as $row){ ?>
							<tr>
								<td><?php echo $i;?></td>
								<td style="font-weight:600;"><?php 
								if(isset($row->unread_admin_status) && $row->unread_admin_status==1){
									
									$color = '#222222';
									$d1 = date('Y-m-d',$row->last_modification_date);
									$chkDays = timeAgoDaysCh($d1,$d2);
									if($chkDays==0){
										$color = '#008000';
									}else if($chkDays==1 || $chkDays==2){
										$color = '#FFBF00';
									}else if($chkDays==3){
										$color = '#FF681F';
									}else if($chkDays>=4){
										$color = '#FF0000';
									}

									?><span style="color: <?php echo $color;?>;font-size:10px;"><i class="fa fa-circle"></i></span> &nbsp;<?php } ?><a class="pro_name" href="<?php echo base_url(). $this->config->item('admin_directory_name');?>tickets/conversations/<?php echo $row->unique_ticket_id;
								// if(isset($row->unread_admin_status) && $row->unread_admin_status==1){echo '?u=1';}?>"><?php echo $row->unique_ticket_id;?></a></td>
								<td><?php echo date('m/d/Y',$row->generated_time);?>  <small><?php echo date('h:i A',$row->generated_time);?></small> </td>
								<td><?php echo $this->config->item('support_types_array_config')[$row->type_of_support]['name'];?></td>
								<td><?php //echo ucwords($row->fullName);									 
									if($row->createdBy==1){
										//echo getStudentNameCh($row->createdById);
										echo '<small>Area Expert</small>';
									}else{
										//echo getFacultyNameCh($row->createdById);
										echo '<small>Project Manager</small>';
									}
								?></td>
								<td><?php echo $row->conversation_cnt;?></td>
								<td><?php echo date('m/d/Y',$row->last_modification_date);?> <small><?php echo date('h:i A',$row->last_modification_date);?></small></td>
								<td><?php if($row->ticket_status==0){?><label class="mstus accepted">Open</label><?php }else{?><label class="mstus rejected">Closed</label><?php } ?></td>
								<td class="action_icons">
									<a class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this ticket?');" href="<?php echo base_url();?>home/ticket_delete?utId=<?php echo $row->unique_ticket_id;?>&r=<?php echo $ticketSecBaseUrl;?>" ><i class="fa fa-trash"></i></a></td>
							</tr>
						<?php $i++;} } ?>
					</tbody>
				</table>
			</div> 
		</div>
	</div>
</section>  