<script type="text/javascript">
function delete_entry(supplier_id){
 	if(supplier_id!="") {
		var r = confirm("Are you sure want to delete it!");
		if (r == true) {
 		  window.location = '<?php echo base_url().$this->config->item('admin_directory_name');?>/suppliers/delete_record?supplier_id='+supplier_id;
 		} 
 	}
} 
function update_toggle_swtich_values(product_id,column_name,site_base_url){
     var checkstatus=$('#toggle-event-'+column_name+product_id).prop('checked');
	 if(checkstatus == true){var update_status=1;}else{var update_status=2;}
	 $.ajax({url: site_base_url+"/suppliers/update_status?supplier_id="+product_id+"&column_name="+column_name+"&update_status="+update_status, 
		beforeSend: function(){ 
			$('#spinner_'+column_name+'_'+product_id).html('<i class="fa fa-spinner fa-spin" aria-hidden="true"></i>');
		},
		success: function(result){
			if(result!=''){
				$('#spinner_'+column_name+'_'+product_id).html('');
			}
		}
	});
}
</script> 
<section class="content">
	 <div class="box">
<style>
.table small {display: block;margin-left: 5px; font-size: 90%;margin-top: 2px;}
.mstus {border: 1px dashed;padding: 1px 10px;margin-bottom: 0;font-size: 14px;}
.accepted {color: green;}
.rejected {color: #a94442;}
</style>	 
		<div class="box-body row">
			<div class="col-xs-12 table-responsive">
				<table class="table table-striped" id="table_recordtbl">
					<thead>
						<tr>
							<th width="1%">#</th>
							<th nowrap="nowrap">Ticket ID</th>
							<th nowrap="nowrap">Type</th>
							<th nowrap="nowrap">Generated By</th>
							<th nowrap="nowrap">Conversation</th>
							<th nowrap="nowrap">Last Update</th>
							<th nowrap="nowrap">Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						<?php if(count($my_tickets_listing)>0){ $i=1;foreach($my_tickets_listing as $row){ ?>
							<tr>
								<td><?php echo $i;?></td>
								<td nowrap="nowrap" style="font-weight:600;"><?php if(isset($row->unread_admin_status) && $row->unread_admin_status==1){?><span style="color:#006738;font-size:10px;"><i class="fa fa-circle"></i></span> &nbsp;<?php } ?><a class="pro_name" href="<?php echo base_url().$this->config->item('admin_directory_name');?>/tickets/conversations/<?php echo $row->unique_ticket_id.'?universityId='.$row->university_id.'&udbname='.$row->sbDatabase.'&tblpre='.$row->sdTblPrefix;
								if(isset($row->unread_admin_status) && $row->unread_admin_status==1){echo '&u=1';}?>"><?php echo $row->unique_ticket_id;?></a>
								<small><?php echo date('m/d/Y, h:i A',$row->generated_time);?></small></td>
								<td><?php echo $this->config->item('support_types_array_config')[$row->type_of_support]['name'];?><small><?php echo '&ndash; '.$this->config->item('support_roles_array_config')[$row->send_message_to]['name'];?></small></td>
								 
								<td><?php echo $row->first_name.' '.$row->last_name;?></td>
								<td><?php echo $row->conversation_cnt;?></td>
								<td><?php echo date('m/d/Y, h:i A',$row->last_modification_date);?></td>
								<td><?php if($row->ticket_status==0){?><label class="mstus accepted">Open</label><?php }else{?><label class="mstus rejected">Closed</label><?php } ?></td>
								<td class="action_icons">
									<a class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this image?');" href="<?php echo base_url();?>my_products/delete/<?php echo $row->id;?>" ><i class="fa fa-trash"></i></a></td>
							</tr>
						<?php $i++;} } ?>
					</tbody>
				</table>
			</div> 
		</div>
	</div>
</section>  